// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace NSViewChangeCursor
{
    public partial class MouseEventView : NSView
    {
        bool changeCursor = false;

        public MouseEventView(IntPtr handle) : base(handle)
        {
        }

        public override void DrawRect(CoreGraphics.CGRect dirtyRect)
        {
            NSColor.Magenta.Set();
            NSGraphics.RectFill(Bounds);
        }

        public override void MouseDown(NSEvent theEvent)
        {
            UpdateCursor(true);
        }

        public override void MouseUp(NSEvent theEvent)
        {
            UpdateCursor(false);
        }

        private void UpdateCursor(bool value)
        {
            changeCursor = value;
            Window.ResetCursorRects();
        }

        public override void ResetCursorRects()
        {
            if (changeCursor)
                AddCursorRect(Bounds, NSCursor.OperationNotAllowedCursor);
        }
    }
}
