// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace NSViewChangeCursor
{
    public partial class RectView : NSView
    {
        public RectView(IntPtr handle) : base(handle)
        {
        }

        public override void DrawRect(CoreGraphics.CGRect dirtyRect)
        {
            NSColor.Cyan.Set();
            NSGraphics.RectFill(this.Bounds);
        }

        public override void ResetCursorRects()
        {
            AddCursorRect(Bounds, NSCursor.ResizeUpDownCursor);
        }
    }
}
