// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using CoreGraphics;

namespace PopupMenuSample
{
    public partial class BlueView : NSView
    {
        public BlueView(IntPtr handle) : base(handle)
        {
        }

        public override void DrawRect(CGRect dirtyRect)
        {
            base.DrawRect(dirtyRect);

            NSColor.Blue.Set();
            NSGraphics.RectFill(dirtyRect);
        }

        public override NSMenu MenuForEvent(NSEvent theEvent)
        {
            var menu = new NSMenu();
            menu.AddItem(
                new NSMenuItem(
                    "Menu Item",
                    (sender, e) => System.Console.WriteLine($"{((NSMenuItem)sender).Title} Clicked")));
            return menu;
        }
    }
}
