// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using CoreGraphics;

namespace PopupMenuSample
{
    public partial class GreenView : NSView
    {
        public GreenView(IntPtr handle) : base(handle)
        {
        }
        public override void DrawRect(CGRect dirtyRect)
        {
            base.DrawRect(dirtyRect);

            NSColor.Green.Set();
            NSGraphics.RectFill(dirtyRect);
        }
    }
}
