// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace ViewScaleSample
{
    public partial class MainView : NSView
    {
        /// <summary>
        /// 表示倍率
        /// </summary>
        public double Scale
        {
            get => scalableView.Scale;
            set => scalableView.Scale = value;
        }
        private ScalableView scalableView;

        public MainView(IntPtr handle) : base(handle)
        {
            scalableView = new ScalableView(this);
        }

        public override void DrawRect(CoreGraphics.CGRect dirtyRect)
        {
            NSColor.Red.SetStroke();
            NSBezierPath.StrokeRect(this.Bounds);

            NSColor.Blue.SetStroke();
            NSBezierPath.StrokeRect(new CoreGraphics.CGRect(10, 10, 10, 10));
        }
    }
}
