// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace NSColorWellSample
{
    public partial class ColorView : NSView
    {
        public NSColor Color
        {
            get => color;
            set
            {
                color = value;
                NeedsDisplay = true;
            }
        }
        private NSColor color = NSColor.White;

        public ColorView(IntPtr handle) : base(handle)
        {
        }

        public override void DrawRect(CoreGraphics.CGRect dirtyRect)
        {
            Color.Set();
            NSGraphics.RectFill(Bounds);
        }
    }
}
