// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace NSViewFrameOriginSample
{
    public partial class MainView : NSView
    {
        public MainView(IntPtr handle) : base(handle)
        {
        }

        public override void DrawRect(CoreGraphics.CGRect dirtyRect)
        {
            NSColor.Red.Set();
            NSBezierPath.StrokeRect(this.Bounds);
        }
    }
}
