// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace NSViewAddConstrains
{
    public partial class BoxView : NSView
    {
        NSColor color;

        public BoxView(IntPtr handle) : base(handle)
        {
            color = NSColor.Gray;
        }

        public BoxView(NSColor color) : base()
        {
            this.color = color;
        }

        public override void DrawRect(CoreGraphics.CGRect dirtyRect)
        {
            color.SetFill();
            NSGraphics.RectFill(this.Bounds);
        }
    }
}
